image:
  pullPolicy: IfNotPresent
  repository: sourcegraph/server
  tag: 5.5.3956@sha256:63409ed4daaed80999969621442b783e24048cfff4845ae31d5f5f6250700584
persistence:
  applicationdatastoragepath:
    enabled: true
    mountPath: /var/opt/sourcegraph
  configstoragepath:
    enabled: true
    mountPath: /etc/sourcegraph
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  adminconsolepo:
    enabled: true
    ports:
      adminconsolepo:
        enabled: true
        port: 2633
        protocol: tcp
        targetPort: 2633
  grafanaport:
    enabled: true
    ports:
      grafanaport:
        enabled: true
        port: 3370
        protocol: tcp
        targetPort: 3370
  main:
    ports:
      main:
        port: 7080
        protocol: http
        targetPort: 7080
