image:
  pullPolicy: IfNotPresent
  repository: mikeah/prusaslicer-novnc
  tag: latest@sha256:f15193f5e43d55923b6cba98a263a0655fa55c6038ce83dad09315a04998f4de
persistence:
  configsfolder:
    enabled: true
    mountPath: /configs/
  prints:
    enabled: true
    mountPath: /prints/
service:
  main:
    ports:
      main:
        port: 16080
        protocol: http
        targetPort: 8080
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
