image:
  repository: ghcr.io/linuxserver/znc
  pullPolicy: IfNotPresent
  tag: 1.9.1@sha256:f6e96fef2485cd70e4d002a8fcd09b2186663a49e9b1b857480348d63c70f230
service:
  main:
    ports:
      main:
        targetPort: 6501
        port: 6501
persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
